### ISSUE TITLE
patch does not apply

### ISSUE THREAD

**Issue by Cubey42** [ashen-sensored/sd_webui_SAG#1]
error: patch failed: modules/script_callbacks.py:53
error: modules/script_callbacks.py: patch does not apply
error: patch failed: modules/sd_samplers_kdiffusion.py:9
error: modules/sd_samplers_kdiffusion.py: patch does not apply

I'm on commit: 22bcc7be428c94e9408f589966c2040187245d81
any suggestions?

**Comment by M-Mahou** [comment]
It means you already applied it ?
you can restore the 2 modified files 
`git restore scripts/script_callbacks.py modules/sd_samplers_kdiffusion.py`
or just check if the files are already edited
`git status`
