### ISSUE TITLE
Patch not applicable with latest version of A1111

### ISSUE THREAD

**Issue by AugmentedRealityCat** [ashen-sensored/sd_webui_SAG#14]
When trying to apply the patch here is the message I get from the GIT command line interface:

```
error: patch failed: modules/sd_samplers_kdiffusion.py:146
error: modules/sd_samplers_kdiffusion.py: patch does not apply
```

A quick look at the A1111 repository confirms that [samplers_kdiffusion.py](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/sd_samplers_kdiffusion.py) has been updated, so I guess that's why the old patch can't be applied "as is" and needs to be updated.

If you try to run the latest A1111 WebUI without the patch, you get the following error message at startup:

```
Error loading script: SAG.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 257, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\stable-diffusion-webui\extensions\sd_webui_SAG\scripts\SAG.py", line 18, in <module>
    from modules.script_callbacks import on_cfg_denoiser,CFGDenoiserParams, CFGDenoisedParams, on_cfg_denoised, AfterCFGCallbackParams, on_cfg_after_cfg
ImportError: cannot import name 'AfterCFGCallbackParams' from 'modules.script_callbacks' (C:\stable-diffusion-webui\modules\script_callbacks.py)
```

**Comment by papuSpartan** [comment]
A PR was very recently merged into the dev branch which I believe should eliminate the need to patch for this extension anymore but I haven't yet tested it.

**Comment by alenknight** [comment]
i'm trying the dev one out now.  seems to work.  yay

**Comment by danielos123ssa** [comment]
sorry new to this how do i install the dev version? thanks in advance

**Comment by alenknight** [comment]
> sorry new to this how do i install the dev version? thanks in advance

type "git checkout dev" in the cmd terminal for sd web ui root folder
but you shouldn't need it anymore. it's been merged into master and works now.  

do git pull to get updated (and hope nothing else breaks... as this happens often... one problem gets fixed... 3 more come)

**Comment by BNP1111** [comment]
> > 抱歉，我是新手，我该如何安装开发版本？  提前致谢
> 
> 在 sd web ui 根文件夹的 cmd 终端中键入“git checkout dev” 但你不应该再需要它了。 它已经合并到 master 中，现在可以工作了。
> 
> 执行 git pull 以获得更新（并希望没有其他问题......因为这种情况经常发生......一个问题得到解决......还有 3 个问题）

no ,still doesnt work

**Comment by Neverdusk** [comment]
I've also been receiving this same error, for both the patch and the UI console. My extension is fully updated, so I'm not fully sure what's wrong.

**Comment by alenknight** [comment]
> I've also been receiving this same error, for both the patch and the UI console. My extension is fully updated, so I'm not fully sure what's wrong.

try deleting your venv and do a fresh install of SAG.... it should be working now... others have noted it's been fixed ... no need to apply patch.

**Comment by Neverdusk** [comment]
> > I've also been receiving this same error, for both the patch and the UI console. My extension is fully updated, so I'm not fully sure what's wrong.
> 
> try deleting your venv and do a fresh install of SAG.... it should be working now... others have noted it's been fixed ... no need to apply patch.

I deleted my venv folder and the extension folder, then reinstall the extension and received the same errors. I'm not sure if I did anything wrong, but this is the only extension that seems to be having errors like this for me.

**Comment by BNP1111** [comment]
not fixed

**Comment by pastuh** [comment]
Install Automatic1111 `DEV` version, and later install SAG as extension.
Works

**Comment by AugmentedRealityCat** [comment]
I was running the DEV version the last time I reported this, but I'll try again with the latest and I'll see if the problem is gone. Thanks for the hint !

**Comment by AugmentedRealityCat** [comment]
Since I already had the dev version installed, I left out that step from the procedure proposed by @pastuh , but I did remove the SAG extension completely, and then I reinstalled it from the A1111-WebUI "extension from URL" tab. And now it works again !
Thanks a lot for providing such a simple and effective solution !

I will close this issue as resolved as it definitely is for me.
