### ISSUE TITLE
Incompatibility with ControlNet reference preprocessors

### ISSUE THREAD

**Issue by catboxanon** [ashen-sensored/sd_webui_SAG#15]
Recently, there have been several new reference preprocessors added to the [ControlNet extension](https://github.com/Mikubill/sd-webui-controlnet). When the Self-Attention Guidance extension is enabled, it either throws exceptions in the console, resulting in no change to the image, or it severely corrupts the image during inference. This looks to be due to the fact ControlNet now implements it's own attention injection procedure.

Related code looks to start at this line (the initial hook seems to be the problem): https://github.com/Mikubill/sd-webui-controlnet/blob/d831043cb81e97724ccf9f071da391d479440a77/scripts/hook.py#L229

https://github.com/Mikubill/sd-webui-controlnet/pull/1235
https://github.com/Mikubill/sd-webui-controlnet/pull/1278

**Comment by alenknight** [comment]
i have this issue too.  works for other controlnet i tested... but all the reference options throw this error....  at least in my case it's consistently this error.

File "C:\AI\stable-diffusion-webui\extensions\sd_webui_SAG\scripts\SAG.py", line 214, in denoised_callback
    attn_mask.reshape(b, middle_layer_latent_size[0], middle_layer_latent_size[1])
RuntimeError: shape '[1, 8, 12]' is invalid for input of size 192

**Comment by alenknight** [comment]
yeah this doesn't work unfortunately.

**Comment by catboxanon** [comment]
Closing, as from my current understanding, there is no straightforward way to resolve this.
