### ISSUE TITLE
does not apply patch after installation, on the right commit

### ISSUE THREAD

**Issue by DoguCatto** [ashen-sensored/sd_webui_SAG#3]
E:\SD2\new web-ui\stable-diffusion-webui\stable-diffusion-webui\stable-diffusion-webui>git apply --ignore-whitespace extensions/sd_webui_SAG/automatic1111-CFGDenoiser-and-script_callbacks-mod-for-SAG.patch
error: patch failed: modules/script_callbacks.py:53
error: modules/script_callbacks.py: patch does not apply
error: patch failed: modules/sd_samplers_kdiffusion.py:9
error: modules/sd_samplers_kdiffusion.py: patch does not apply

E:\SD2\new web-ui\stable-diffusion-webui\stable-diffusion-webui\stable-diffusion-webui>

**Comment by ptrprkr** [comment]
same issue here

**Comment by crypticnull** [comment]
Also experiencing this.

**Comment by ashen-sensored** [comment]
Vlad fork no longer requires patching since the change has already been merged to upstream in commit  [cb465b1](https://github.com/vladmandic/automatic/commit/cb465b12ddc5e4b5f6566030021a26630b927ba6), I'll update README to reflect the changes.

**Comment by sdbds** [comment]
it works well even show errors for patch.

**Comment by ashen-sensored** [comment]
> it works well even show errors for patch.

It will show error if you apply the patch again. You only need to run the command once.

**Comment by DoguCatto** [comment]
@ashen-sensored  can you add a message "patch already applied"? 
this will help with the confusion
