### ISSUE TITLE
automatic1111 webui  a9eab236d7e8afa4d6205127904a385b2c43bb24 Can it be used？

### ISSUE THREAD

**Issue by iconnoci** [ashen-sensored/sd_webui_SAG#7]
automatic1111 webui   a9eab236d7e8afa4d6205127904a385b2c43bb24  Can it be used? I don’t want to upgrade to the latest version. When it draws a picture, it doesn’t show up sometimes. For me

**Comment by Sakura-Luna** [comment]
https://github.com/ashen-sensored/sd_webui_SAG/pull/4
