### ISSUE TITLE
Instead of a patch, why not submit a PR?

### ISSUE THREAD

**Issue by missionfloyd** [ashen-sensored/sd_webui_SAG#8]
Other than the fact that it'll probably sit in the queue for a while, that is.

**Comment by ashen-sensored** [comment]
I submitted the patch to vlad's fork and it's already merged to upstream, so the patch for vlad's fork is no longer needed.
I don't know if a111 will ever come back though.

**Comment by Panchovix** [comment]
It seems a111 is back, at least on the dev branch

https://github.com/AUTOMATIC1111/stable-diffusion-webui/commits/dev

The patch doesn't work, so I had to do the changes manually in the files
